[project]
name = ""
version = ""
description = ""
authors = [
    {name = "spencercarroll", email = "spencerjcarroll@gmail.com"},
]
dependencies = [
    "django>=4.2.7",
    "python-dotenv>=1.0.0",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

