[project]
name = ""
version = ""
description = ""
authors = [
    {name = "spencercarroll", email = "spencerjcarroll@gmail.com"},
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

